name: book_tracker
description: A Book Tracker app for UAS - Provider, API, SQLite, CRUD, Dark Mode, Animations, Dashboard stats
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  http: ^0.13.6
  sqflite: ^2.2.8
  path_provider: ^2.0.14
  shared_preferences: ^2.1.1
  fl_chart: ^0.63.0
  intl: ^0.18.0
  url_launcher: ^6.1.10

flutter:
  uses-material-design: true
  assets:
    - assets/